run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  relative-path-mode: gomod

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - misspell
      text: "`thn` is a misspelling of `then`"

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused

linters-settings:
  misspell:
    locale: US
